# Default values for hello-app.
# These are the values used unless overridden (e.g. with -f values-prod.yaml or --set).

backend:
  replicaCount: 3
  image:
    repository: new-backend-image
    tag: latest
    pullPolicy: Never
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

frontend:
  replicaCount: 1
  image:
    repository: new-frontend-image
    tag: latest
    pullPolicy: Never

ingress:
  className: nginx
  backendHost: myappapi.com
  frontendHost: myappfrontend.com